// Cycle-accurate dual-clock async FIFO (Cummings-style: binary + Gray-coded
// pointers, N-stage synchronizer shift registers for each pointer crossing
// into the opposite clock domain).
//
// Implementation note: this is a plain C++ class, not an sc_module with
// clocked ports. It is driven by EXPLICIT calls -- on_wr_edge() once per
// writer-domain clock edge, on_rd_edge() once per reader-domain clock edge --
// made from the SystemC testbench's own per-domain SC_THREAD processes (see
// sc/mesh_tb.cpp). This sidesteps the classic SystemC same-delta-cycle
// signal-visibility ordering hazard that a naive two sc_module, port-connected
// design would hit if both the "driver" and the "AFIFO" were SC_METHODs
// sensitive to the very same clock edge event. The clock edges themselves are
// still generated by real SystemC processes with independent phase/jitter via
// sc_time/wait(), so the CDC timing (S-stage synchronizer latency, one flit
// drained per reader edge, one flit accepted per writer edge) is fully
// cycle-accurate; only the "port wiring" is simplified to method calls.
#pragma once

#include <cstdint>
#include <vector>

class AsyncFifo {
 public:
  AsyncFifo(int depth, int sync_stages)
      : depth_(depth), stages_(sync_stages), mem_(depth) {
    wsync_chain_.assign(stages_, 0);  // rptr_gray shifted into write domain
    rsync_chain_.assign(stages_, 0);  // wptr_gray shifted into read domain
  }

  // One writer-domain clock edge. If wr_en and the FIFO is not full, the
  // flit is accepted and `true` is returned; otherwise (wr_en && full) the
  // write stalls this cycle (counted) and `false` is returned.
  bool on_wr_edge(bool wr_en, int data) {
    // Shift the async rptr_gray sample through the write-domain sync chain.
    for (int i = stages_ - 1; i > 0; --i) wsync_chain_[i] = wsync_chain_[i - 1];
    if (stages_ > 0) wsync_chain_[0] = rptr_gray_;
    unsigned synced_rptr_gray = (stages_ > 0) ? wsync_chain_[stages_ - 1]
                                              : rptr_gray_;
    unsigned rptr_bin_sync = gray2bin(synced_rptr_gray);
    unsigned used = wrap(wptr_bin_ - rptr_bin_sync);
    bool full = used >= (unsigned)depth_;

    if (wr_en && !full) {
      mem_[wptr_bin_ % depth_] = data;
      wptr_bin_ = wrap(wptr_bin_ + 1);
      wptr_gray_ = bin2gray(wptr_bin_);
      ++write_count_;
      update_phys_peak();
      return true;
    }
    if (wr_en && full) ++wstall_count_;
    return false;
  }

  // One reader-domain clock edge. If rd_en and the FIFO is not empty, a flit
  // is drained (data_out set) and `true` is returned; else `false`.
  bool on_rd_edge(bool rd_en, int* data_out) {
    for (int i = stages_ - 1; i > 0; --i) rsync_chain_[i] = rsync_chain_[i - 1];
    if (stages_ > 0) rsync_chain_[0] = wptr_gray_;
    unsigned synced_wptr_gray = (stages_ > 0) ? rsync_chain_[stages_ - 1]
                                              : wptr_gray_;
    unsigned wptr_bin_sync = gray2bin(synced_wptr_gray);
    bool empty = (wptr_bin_sync == rptr_bin_);

    bool did_read = false;
    if (rd_en && !empty) {
      if (data_out) *data_out = mem_[rptr_bin_ % depth_];
      rptr_bin_ = wrap(rptr_bin_ + 1);
      rptr_gray_ = bin2gray(rptr_bin_);
      ++read_count_;
      did_read = true;
    }
    unsigned occ_now = wrap(wptr_bin_sync - rptr_bin_);
    if ((int)occ_now > peak_occ_) peak_occ_ = (int)occ_now;
    last_occ_ = (int)occ_now;
    update_phys_peak();
    return did_read;
  }

  int depth() const { return depth_; }
  int sync_stages() const { return stages_; }
  long write_count() const { return write_count_; }
  long read_count() const { return read_count_; }
  long wstall_count() const { return wstall_count_; }
  // "Visible" occupancy: wptr as seen through the reader-domain sync chain
  // minus rptr. This is what the FIFO's own empty/full logic uses; it lags
  // the true fill level by up to `sync_stages` cycles (a write isn't
  // "visible" to the reader until it has propagated through the chain).
  int peak_occ() const { return peak_occ_; }
  int last_occ() const { return last_occ_; }
  // TRUE physical fill level (wptr_bin_ - rptr_bin_, no sync-chain lag). This
  // is the number of flit slots the physical memory array must actually hold,
  // i.e. the real buffer-cost / provisioning number.
  int peak_phys_occ() const { return peak_phys_occ_; }

 private:
  void update_phys_peak() {
    unsigned phys = wrap(wptr_bin_ - rptr_bin_);
    if ((int)phys > peak_phys_occ_) peak_phys_occ_ = (int)phys;
  }
  static constexpr unsigned kPtrBits = 12;      // supports depth up to 2^11
  static constexpr unsigned kPtrMod = 1u << kPtrBits;

  static unsigned bin2gray(unsigned b) { return b ^ (b >> 1); }
  static unsigned gray2bin(unsigned g) {
    unsigned b = 0;
    for (; g; g >>= 1) b ^= g;
    return b;
  }
  static unsigned wrap(unsigned x) { return x & (kPtrMod - 1); }

  int depth_;
  int stages_;
  std::vector<int> mem_;

  unsigned wptr_bin_ = 0, rptr_bin_ = 0;
  unsigned wptr_gray_ = 0, rptr_gray_ = 0;
  std::vector<unsigned> wsync_chain_;  // S flops, clocked by wr_clk
  std::vector<unsigned> rsync_chain_;  // S flops, clocked by rd_clk

  long write_count_ = 0, read_count_ = 0, wstall_count_ = 0;
  int peak_occ_ = 0, last_occ_ = 0, peak_phys_occ_ = 0;
};
