// Cycle-level SystemC testbench for the cross-reticle AFIFO CDC study.
//
// Replays a full per-link send trace (produced by utils/export_sc_trace.py)
// for a 4x4 mesh (reticle = quadrant = 2x2, boundary at col/row 1|2) over four
// independent, mesochronous (same nominal frequency, independent static phase
// + bounded per-cycle phase wander/jitter) clock domains, one per reticle.
// Every directed link that crosses a reticle boundary is routed through an
// AsyncFifo (sc/afifo.h) instead of being a plain wire.
//
// Two AFIFO read policies are compared:
//   greedy : read out of the AFIFO as soon as it is non-empty, regardless of
//            whether the destination node's own outgoing links are already
//            busy carrying other (locally-scheduled) traffic this cycle. If a
//            read fires while the destination has no spare output slot, it is
//            counted as a COLLISION (informational: a real 0-buffer router
//            would need extra input buffering to absorb this).
//   gated  : only read when the destination node has a free output slot this
//            cycle ("slot-gated"). Guarantees zero collisions by construction,
//            at the cost of extra AFIFO occupancy (reads are delayed) and
//            possibly extra writer-side stalls if the AFIFO then fills up.
//
// "Destination free slot" is derived directly from the REPLAYED FULL trace:
// deg_out[c] = number of distinct outgoing links c uses anywhere in the
// original rigid schedule; busy[c][t] = how many of those are active at
// cycle t. slot_free(c,t) = busy[c][t] < deg_out[c] (always free if c has no
// outgoing links).
//
// The AsyncFifo itself is a real Cummings-style dual binary/Gray pointer async
// FIFO with an S-stage synchronizer shift register per pointer crossing (see
// sc/afifo.h); the clock edges that drive it are generated by genuine SystemC
// per-domain SC_THREAD processes using sc_time/wait(), with independent phase
// and jitter -- so the CDC latency and occupancy behavior are cycle-accurate,
// not just an analytic approximation.

#include <systemc.h>

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <map>
#include <memory>
#include <random>
#include <set>
#include <sstream>
#include <string>
#include <vector>

#include "afifo.h"

// Per-AFIFO VCD trace bundle. Writer-side and reader-side signals are updated
// ONLY by their respective clock-domain SC_THREAD (sc_signal allows one driver).
struct AfifoTrace {
  sc_signal<int> wr_occ_phys;
  sc_signal<int> wr_en;
  sc_signal<int> wr_ok;
  sc_signal<int> wr_stall;
  sc_signal<int> rd_occ_phys;
  sc_signal<int> rd_occ_vis;
  sc_signal<int> rd_en;
  sc_signal<int> rd_ok;
  sc_signal<int> slot_free;
};

struct DomainTrace {
  sc_signal<int> cycle;
};

// ---------------------------------------------------------------------------
struct Trace {
  int mx = 0, my = 0, h = 0, v = 0, ramp = 0, makespan = 0;
  // ALL directed link events (p, c, send, src), any position in the mesh.
  std::vector<std::tuple<int, int, int, int>> events;
};

static Trace load_trace(const std::string& path) {
  Trace t;
  std::ifstream f(path);
  if (!f) {
    std::fprintf(stderr, "cannot open trace file: %s\n", path.c_str());
    std::exit(2);
  }
  std::string line;
  int nevents = -1;
  while (std::getline(f, line)) {
    if (line.empty() || line[0] == '#') continue;
    std::istringstream is(line);
    std::string key;
    is >> key;
    if (key == "MX") is >> t.mx;
    else if (key == "MY") is >> t.my;
    else if (key == "H") is >> t.h;
    else if (key == "V") is >> t.v;
    else if (key == "RAMP") is >> t.ramp;
    else if (key == "MAKESPAN") is >> t.makespan;
    else if (key == "NEVENTS") { is >> nevents; break; }
  }
  if (nevents < 0) {
    std::fprintf(stderr, "malformed trace (no NEVENTS): %s\n", path.c_str());
    std::exit(2);
  }
  t.events.reserve(nevents);
  while (std::getline(f, line)) {
    if (line.empty() || line[0] == '#') continue;
    std::istringstream is(line);
    int p, c, send, src;
    if (!(is >> p >> c >> send >> src)) continue;
    t.events.emplace_back(p, c, send, src);
  }
  return t;
}

static inline int quad_of(int node, int mx, int my) {
  int x = node % mx, y = node / mx;
  return (x < mx / 2 ? 0 : 1) + (y < my / 2 ? 0 : 2);
}

// ---------------------------------------------------------------------------
struct CrossLink {
  int p, c, wdom, rdom;
  int trace_idx = -1;
  std::vector<int> sends;   // sorted scheduled write cycles (domain-local idx)
  size_t next_send_idx = 0;
  AsyncFifo* fifo = nullptr;
  AfifoTrace* trace = nullptr;
  long collisions = 0;
  long delivered_count = 0;
  int last_delivered = -1;
  int first_send = -1;
};

// ---------------------------------------------------------------------------
struct Args {
  std::string trace;
  std::string scheme = "unknown";
  std::string policy = "greedy";
  double sigma = 0.0;
  int sync = 2;
  int depth = 4;
  unsigned seed = 1;
  int margin = 120;
  bool phase0 = false;
  double force_phase_eps = -1.0;  // if >=0, override all non-ref phases (debug)
  std::string vcd_path;          // empty => no waveform dump
  int vcd_busiest = 4;           // when --vcd: trace only the N busiest AFIFOs
};

static Args parse_args(int argc, char** argv) {
  Args a;
  for (int i = 1; i < argc; ++i) {
    std::string s = argv[i];
    auto next = [&]() -> std::string { return (i + 1 < argc) ? argv[++i] : ""; };
    if (s == "--trace") a.trace = next();
    else if (s == "--scheme") a.scheme = next();
    else if (s == "--policy") a.policy = next();
    else if (s == "--sigma") a.sigma = std::atof(next().c_str());
    else if (s == "--sync") a.sync = std::atoi(next().c_str());
    else if (s == "--depth") a.depth = std::atoi(next().c_str());
    else if (s == "--seed") a.seed = (unsigned)std::atoi(next().c_str());
    else if (s == "--margin") a.margin = std::atoi(next().c_str());
    else if (s == "--phase0") a.phase0 = true;
    else if (s == "--force-phase-eps") a.force_phase_eps = std::atof(next().c_str());
    else if (s == "--vcd") a.vcd_path = next();
    else if (s == "--vcd-busiest") a.vcd_busiest = std::atoi(next().c_str());
  }
  if (a.trace.empty()) {
    std::fprintf(stderr, "usage: mesh_tb --trace <path> [--scheme ring|hybrid] "
                          "[--policy greedy|gated] [--sigma f] [--sync i] "
                          "[--depth i] [--seed u] [--margin i] [--phase0] "
                          "[--vcd <file>] [--vcd-busiest N]\n");
    std::exit(2);
  }
  return a;
}

// ---------------------------------------------------------------------------
// One clock domain (= one reticle). Drives its own writer-side and reader-side
// cross-links once per (jittered, phase-offset) clock edge.
SC_MODULE(Domain) {
  SC_HAS_PROCESS(Domain);
  Domain(sc_module_name nm, int id_, double phase0_, double sigma_,
         long total_edges_, const std::string& policy_, unsigned seed_,
         DomainTrace* dom_trace_)
      : sc_module(nm), id(id_), phase0(phase0_), sigma(sigma_),
        total_edges(total_edges_), policy(policy_), rng(seed_),
        dom_trace(dom_trace_) {
    SC_THREAD(proc);
  }

  int id;
  double phase0;                 // initial static phase, units of period
  double sigma;                  // jitter std-dev per cycle, units of period
  long total_edges;
  std::string policy;
  std::mt19937 rng;
  DomainTrace* dom_trace;

  std::vector<CrossLink*> as_writer;
  std::vector<CrossLink*> as_reader;
  // node -> per-cycle "downstream free slot" (index by cycle; sized by caller)
  std::map<int, std::vector<char>> slot_free;
  long cycle = 0;

  static void update_afifo_wr_trace(CrossLink* cl) {
    if (!cl || !cl->trace || !cl->fifo) return;
    AfifoTrace& t = *cl->trace;
    t.wr_occ_phys.write(cl->fifo->phys_occ_now());
    t.wr_en.write(cl->fifo->last_wr_en() ? 1 : 0);
    t.wr_ok.write(cl->fifo->last_wr_ok() ? 1 : 0);
    t.wr_stall.write((cl->fifo->last_wr_en() && !cl->fifo->last_wr_ok()) ? 1 : 0);
  }

  static void update_afifo_rd_trace(CrossLink* cl, bool slot_ok) {
    if (!cl || !cl->trace || !cl->fifo) return;
    AfifoTrace& t = *cl->trace;
    t.rd_occ_phys.write(cl->fifo->phys_occ_now());
    t.rd_occ_vis.write(cl->fifo->last_occ());
    t.rd_en.write(cl->fifo->last_rd_en() ? 1 : 0);
    t.rd_ok.write(cl->fifo->last_rd_ok() ? 1 : 0);
    t.slot_free.write(slot_ok ? 1 : 0);
  }

  void proc() {
    const double period_ps = 1000.0;  // 1 ns nominal period, traced in ps
    std::normal_distribution<double> gauss(0.0, sigma);
    double phase_state = std::max(-0.5, std::min(0.5, phase0));

    double first_wait = phase_state;  // in UI (fraction of period)
    if (first_wait < 0) first_wait += 1.0;
    wait(sc_time(first_wait * period_ps, SC_PS));

    for (long e = 0; e < total_edges; ++e) {
      if (dom_trace) dom_trace->cycle.write((int)cycle);

      // ---- writer side: push any overdue sends into their AFIFOs ----
      for (auto* cl : as_writer) {
        bool wr_en = (cl->next_send_idx < cl->sends.size() &&
                      cl->sends[cl->next_send_idx] <= cycle);
        bool wrote = cl->fifo->on_wr_edge(wr_en, cl->p);
        if (wr_en && wrote) ++cl->next_send_idx;
        update_afifo_wr_trace(cl);
      }
      // ---- reader side: drain per policy ----
      for (auto* cl : as_reader) {
        bool slot_ok = true;
        auto it = slot_free.find(cl->c);
        if (it != slot_free.end() && cycle >= 0 &&
            (size_t)cycle < it->second.size())
          slot_ok = it->second[cycle] != 0;
        bool rd_en = (policy == "greedy") ? true : slot_ok;
        int data = -1;
        bool read = cl->fifo->on_rd_edge(rd_en, &data);
        if (read) {
          ++cl->delivered_count;
          cl->last_delivered = (int)cycle;
          if (policy == "greedy" && !slot_ok) ++cl->collisions;
        }
        update_afifo_rd_trace(cl, slot_ok);
      }
      ++cycle;
      // ---- advance to next edge with bounded phase wander ----
      double wander = (sigma > 0.0) ? gauss(rng) : 0.0;
      double new_phase = std::max(-0.5, std::min(0.5, phase_state + wander));
      double dt_ui = 1.0 + (new_phase - phase_state);  // period + phase delta, in UI
      phase_state = new_phase;
      const double floor_ui = 0.05;
      if (dt_ui < floor_ui) dt_ui = floor_ui;
      wait(sc_time(dt_ui * period_ps, SC_PS));
    }
  }
};

// ---------------------------------------------------------------------------
int sc_main(int argc, char** argv) {
  Args args = parse_args(argc, argv);
  Trace tr = load_trace(args.trace);
  const int mx = tr.mx, my = tr.my, N = mx * my;

  // ALL-link occupancy (for downstream slot-free derivation) + cross-link list
  std::map<std::pair<int, int>, std::vector<int>> all_link_sends;
  for (auto& [p, c, send, src] : tr.events) {
    (void)src;
    all_link_sends[{p, c}].push_back(send);
  }
  for (auto& kv : all_link_sends) std::sort(kv.second.begin(), kv.second.end());

  std::vector<std::set<int>> out_nbrs(N);
  for (auto& kv : all_link_sends) out_nbrs[kv.first.first].insert(kv.first.second);

  const int max_cycle = tr.makespan + args.margin;
  std::vector<std::vector<char>> busy(N, std::vector<char>(max_cycle + 1, 0));
  for (auto& kv : all_link_sends) {
    int p = kv.first.first;
    for (int t : kv.second) if (t >= 0 && t <= max_cycle) busy[p][t]++;
  }
  std::vector<int> deg_out(N);
  for (int n = 0; n < N; ++n) deg_out[n] = (int)out_nbrs[n].size();

  std::vector<std::vector<char>> slot_free(N, std::vector<char>(max_cycle + 1, 1));
  for (int n = 0; n < N; ++n) {
    if (deg_out[n] == 0) continue;  // always free (no output to protect)
    for (int t = 0; t <= max_cycle; ++t)
      slot_free[n][t] = (busy[n][t] < deg_out[n]) ? 1 : 0;
  }

  std::vector<CrossLink> cross_links;
  for (auto& kv : all_link_sends) {
    int p = kv.first.first, c = kv.first.second;
    int wdom = quad_of(p, mx, my), rdom = quad_of(c, mx, my);
    if (wdom == rdom) continue;  // intra-reticle link, plain wire (not modeled)
    CrossLink cl;
    cl.p = p; cl.c = c; cl.wdom = wdom; cl.rdom = rdom;
    cl.sends = kv.second;
    cl.first_send = cl.sends.empty() ? -1 : cl.sends.front();
    cross_links.push_back(std::move(cl));
  }
  std::vector<AsyncFifo> fifos;
  fifos.reserve(cross_links.size());
  for (size_t i = 0; i < cross_links.size(); ++i)
    fifos.emplace_back(args.depth, args.sync);
  for (size_t i = 0; i < cross_links.size(); ++i)
    cross_links[i].fifo = &fifos[i];

  // ---- optional VCD waveform dump (gtkwave); trace only selected AFIFOs ----
  std::vector<std::unique_ptr<AfifoTrace>> afifo_traces;
  std::vector<DomainTrace> dom_traces(4);
  sc_trace_file* tf = nullptr;
  std::string vcd_base;
  std::vector<size_t> vcd_indices;
  if (!args.vcd_path.empty()) {
    // Rank cross-links by traffic volume; pick top N for waveform.
    std::vector<size_t> order(cross_links.size());
    for (size_t i = 0; i < order.size(); ++i) order[i] = i;
    std::sort(order.begin(), order.end(), [&](size_t a, size_t b) {
      return cross_links[a].sends.size() > cross_links[b].sends.size();
    });
    int ntrace = args.vcd_busiest;
    if (ntrace <= 0 || ntrace > (int)cross_links.size())
      ntrace = (int)cross_links.size();
    for (int k = 0; k < ntrace; ++k) vcd_indices.push_back(order[k]);

    vcd_base = args.vcd_path;
    if (vcd_base.size() > 4 &&
        vcd_base.compare(vcd_base.size() - 4, 4, ".vcd") == 0)
      vcd_base = vcd_base.substr(0, vcd_base.size() - 4);
    tf = sc_create_vcd_trace_file(vcd_base.c_str());
    tf->set_time_unit(1, SC_PS);
    for (int d = 0; d < 4; ++d) {
      char nm[32];
      std::snprintf(nm, sizeof(nm), "dom%d_cyc", d);
      sc_trace(tf, dom_traces[d].cycle, nm);
    }
    for (size_t ki = 0; ki < vcd_indices.size(); ++ki) {
      size_t i = vcd_indices[ki];
      afifo_traces.emplace_back(std::make_unique<AfifoTrace>());
      cross_links[i].trace_idx = (int)i;
      cross_links[i].trace = afifo_traces.back().get();
      AfifoTrace& at = *afifo_traces.back();
      auto& cl = cross_links[i];
      char pre[64];
      std::snprintf(pre, sizeof(pre), "afifo%zu_p%d_c%d", ki, cl.p, cl.c);
      char nm[80];
      auto reg = [&](sc_signal<int>& sig, const char* suffix) {
        std::snprintf(nm, sizeof(nm), "%s_%s", pre, suffix);
        sc_trace(tf, sig, nm);
      };
      reg(at.wr_occ_phys, "wr_occ_phys");
      reg(at.wr_en, "wr_en");
      reg(at.wr_ok, "wr_ok");
      reg(at.wr_stall, "wr_stall");
      reg(at.rd_occ_phys, "rd_occ_phys");
      reg(at.rd_occ_vis, "rd_occ_vis");
      reg(at.rd_en, "rd_en");
      reg(at.rd_ok, "rd_ok");
      reg(at.slot_free, "slot_free");
    }
    std::printf("VCD: %s.vcd  (gtkwave %s.vcd)  tracing %zu/%zu AFIFOs\n",
                vcd_base.c_str(), vcd_base.c_str(),
                vcd_indices.size(), cross_links.size());
    for (size_t ki = 0; ki < vcd_indices.size(); ++ki) {
      auto& cl = cross_links[vcd_indices[ki]];
      std::printf("  VCD_AFIFO[%zu] p=%d c=%d nsend=%zu wdom=%d rdom=%d\n",
                  ki, cl.p, cl.c, cl.sends.size(), cl.wdom, cl.rdom);
    }
  }

  // ---- domains ----
  std::mt19937 master(args.seed);
  std::uniform_real_distribution<double> uphase(-0.5, 0.5);
  std::vector<double> dom_phase(4, 0.0);
  std::vector<unsigned> dom_seed(4);
  for (int d = 0; d < 4; ++d) {
    double ph = 0.0;
    if (!args.phase0) {
      ph = (d == 0) ? 0.0 : uphase(master);
      if (args.force_phase_eps >= 0.0 && d != 0) ph = args.force_phase_eps;
    } else if (args.force_phase_eps >= 0.0) {
      ph = args.force_phase_eps;
    }
    dom_phase[d] = ph;
    dom_seed[d] = master();
  }

  const long total_edges = max_cycle + 1;
  std::vector<Domain*> domains(4);
  for (int d = 0; d < 4; ++d) {
    char nm[32];
    std::snprintf(nm, sizeof(nm), "dom_%d", d);
    domains[d] = new Domain(nm, d, dom_phase[d], args.sigma, total_edges,
                            args.policy, dom_seed[d], &dom_traces[d]);
  }
  for (auto& cl : cross_links) {
    domains[cl.wdom]->as_writer.push_back(&cl);
    domains[cl.rdom]->as_reader.push_back(&cl);
  }
  for (int d = 0; d < 4; ++d) {
    for (auto* cl : domains[d]->as_reader)
      domains[d]->slot_free[cl->c] = slot_free[cl->c];
  }

  sc_start();

  // ---- collect stats ----
  long total_writes = 0, total_reads = 0, total_wstall = 0, total_collisions = 0;
  int peak_occ_max = 0, peak_phys_occ_max = 0, last_delivered_max = 0;
  long total_buf_flits = 0;  // sum of per-link physical peak occupancy
  bool mass_ok = true;
  for (auto& cl : cross_links) {
    total_writes += cl.fifo->write_count();
    total_reads += cl.fifo->read_count();
    total_wstall += cl.fifo->wstall_count();
    total_collisions += cl.collisions;
    peak_occ_max = std::max(peak_occ_max, cl.fifo->peak_occ());
    peak_phys_occ_max = std::max(peak_phys_occ_max, cl.fifo->peak_phys_occ());
    total_buf_flits += cl.fifo->peak_phys_occ();
    last_delivered_max = std::max(last_delivered_max, cl.last_delivered);
    if (cl.fifo->write_count() != cl.fifo->read_count()) mass_ok = false;
  }

  std::printf("SUMMARY scheme=%s policy=%s sigma=%.3f sync=%d depth=%d seed=%u "
              "ncross=%zu total_writes=%ld total_reads=%ld total_wstall=%ld "
              "total_collisions=%ld peak_occ_max=%d peak_phys_occ_max=%d "
              "total_buf_flits=%ld last_delivered_max=%d mass_ok=%d "
              "makespan_trace=%d\n",
              args.scheme.c_str(), args.policy.c_str(), args.sigma, args.sync,
              args.depth, args.seed, cross_links.size(), total_writes,
              total_reads, total_wstall, total_collisions, peak_occ_max,
              peak_phys_occ_max, total_buf_flits, last_delivered_max,
              mass_ok ? 1 : 0, tr.makespan);
  for (auto& cl : cross_links) {
    std::printf("LINK p=%d c=%d wdom=%d rdom=%d nsend=%zu peak_occ=%d "
                "peak_phys_occ=%d writes=%ld reads=%ld wstall=%ld "
                "collisions=%ld first_send=%d last_delivered=%d\n",
                cl.p, cl.c, cl.wdom, cl.rdom, cl.sends.size(),
                cl.fifo->peak_occ(), cl.fifo->peak_phys_occ(),
                cl.fifo->write_count(), cl.fifo->read_count(),
                cl.fifo->wstall_count(), cl.collisions, cl.first_send,
                cl.last_delivered);
  }

  for (auto* d : domains) delete d;
  if (tf) sc_close_vcd_trace_file(tf);
  return 0;
}
