#!/usr/bin/env python3
"""Generate HTML report for BookSim trace verification (Route A + B)."""

import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SWEEP_JSON = ROOT / "results" / "booksim_trace_sweep.json"
EXPORT_JSON = ROOT / "results" / "traces" / "6x8" / "export_summary.json"
HTML_PATH = ROOT / "results" / "report_booksim_trace_6x8.html"

CSS = """
body{font-family:system-ui,sans-serif;margin:24px 32px;line-height:1.6;max-width:1100px}
h1{margin:0 0 8px} h2{color:#1e3a8a;border-top:1px solid #e2e8f0;padding-top:18px}
.card{background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:18px 22px;margin:14px 0}
table{border-collapse:collapse;width:100%;font-size:.82rem}
th,td{border:1px solid #e2e8f0;padding:5px 8px;text-align:center}
th{background:#f1f5f9}.name{text-align:left}
.good{background:#ecfdf5}.warn{background:#fef3c7}.bad{background:#fee2e2}
.meta{color:#64748b;font-size:.9rem}
code{background:#f1f5f9;padding:1px 5px;border-radius:4px}
"""


def esc(s):
    return html.escape(str(s))


def main():
    sweep = json.loads(SWEEP_JSON.read_text(encoding="utf-8")) if SWEEP_JSON.exists() else []
    export = { (e["scheme"], e["ramp_bw"], e["m"]): e for e in json.loads(EXPORT_JSON.read_text()) if e.get("ok")}

    by_key = {}
    for r in sweep:
        k = (r["scheme"], r["ramp_bw"], r["m"], r["route"])
        by_key[k] = r

    tbody = []
    for (scheme, rb, m), meta in sorted(export.items()):
        exp = meta["expected_makespan"]
        ah = by_key.get((scheme, rb, m, "A_hop"), {})
        bt = by_key.get((scheme, rb, m, "B_tree"), {})
        a_mk = ah.get("sim_makespan")
        b_mk = bt.get("sim_makespan")
        a_st = ah.get("buffer_full_stalls")
        b_st = bt.get("buffer_full_stalls")
        a_ok = ah.get("ok")
        b_ok = bt.get("ok")
        cls = "good" if a_st == 0 and b_st == 0 else "warn"
        tbody.append(
            f"<tr class='{cls}'><td class='name'>{esc(scheme)}</td><td>{rb}</td><td>{m}</td>"
            f"<td>{exp}</td><td>{a_mk}</td><td>{b_mk}</td><td>{a_st}</td><td>{b_st}</td>"
            f"<td>{'Y' if a_ok else 'N'}</td><td>{'Y' if b_ok else 'N'}</td></tr>"
        )

    html_doc = f"""<!DOCTYPE html>
<html lang="zh-CN"><head><meta charset="utf-8"/><title>BookSim2 Trace 验证 6x8</title>
<style>{CSS}</style></head><body>
<h1>BookSim2 真实 Router 微架构验证 — 6×8</h1>
<p class="meta">Route A：逐 hop trace + IQ router。Route B：tree inject + fork 表 token 展开（TraceTrafficManager）+ 每 hop 走 IQ router；ForkIQRouter 已实现（router=fork_iq）但 VC/credit 下仍有协议问题，本报告 Route B 采用 TM 侧 fork 展开。</p>
<div class="card">
<h2>配置</h2>
<ul>
<li>拓扑：<code>runfiles/mesh_6x8.anynet</code>（H=4, V=6, ramp=1）</li>
<li>Router：IQ，<code>vc_buf_size=1</code>，<code>routing/sw/vc_alloc_delay=1</code></li>
<li>判定：allgather 收齐 (N-1)×m flit/节点，<code>buffer_full_stalls=0</code> 为 0-buffer 佐证</li>
<li>makespan 偏差：BookSim 流水线 + credit 往返相对 Python 刚性模型的固定/缓变 overhead</li>
</ul>
</div>
<div class="card">
<h2>全量扫描结果</h2>
<table><thead><tr>
<th class="name">方案</th><th>rb</th><th>m</th><th>Python mk</th>
<th>A sim mk</th><th>B sim mk</th><th>A stalls</th><th>B stalls</th><th>A ok</th><th>B ok</th>
</tr></thead><tbody>{''.join(tbody)}</tbody></table>
</div>
<div class="card">
<h2>结论</h2>
<ul>
<li><b>Route A</b> 在 0-buffer 调度点上普遍 <code>stalls=0</code>，验证 Python 链路无冲突假设在真实 IQ 微架构下成立（makespan 需加 pipeline 常数）。</li>
<li><b>Route B</b> 以 tree 语义驱动 token 展开 + 真实逐 hop 转发，makespan 与 A 同量级；与 Python 模型偏差主要来自 router 延迟建模差异。</li>
<li><b>ForkIQRouter</b>（硬件 fork 原型）已合入 <code>src/routers/fork_iq_router.cpp</code>，待 VC/credit 与单输入多副本时序对齐后可切换 <code>router=fork_iq</code> 做纯硬件 fork 试验。</li>
</ul>
</div>
<p class="meta">Generated by utils/gen_booksim_trace_report.py</p>
</body></html>"""
    HTML_PATH.write_text(html_doc, encoding="utf-8")
    print(f"Wrote {HTML_PATH}")


if __name__ == "__main__":
    main()
