#!/usr/bin/env python3
"""Cross-validate `mesh_base` against stock BookSim on the same 8x6 mesh.

Why anynet and not `topology = mesh`
-----------------------------------
BookSim's built-in mesh is a k-ary n-cube with a single radix k, so an 8x6 mesh
is not expressible (see `src/networks/kncube.cpp`). `anynet` takes an explicit
adjacency list with per-link latency, which also lets the H=7 / V=9 asymmetry be
stated exactly rather than approximated by a uniform hop delay.

What is being validated
-----------------------
Only `mesh_base`: a buffered input-queued mesh with XY routing, credit-based
flow control and an iSLIP switch allocator. That is the one configuration in
this study that stock BookSim can also express, so it is the only place an
independent implementation can check ours. The bufferless ring and both
centralized request-grant variants have no BookSim equivalent -- there is no
model in the simulator for a global reservation table or for boarding/leaving
arbitration -- so they are validated against analytic bounds and against the
per-clause conflict checkers instead.

Agreement criterion
-------------------
Zero-load latency within a couple of cycles (this is a pure wire-delay sum, so
a mismatch means the topology file is wrong), and saturation throughput within
about 10%. Beyond that the two models legitimately diverge: BookSim charges
router pipeline stages that our cycle model folds into the link latency.

Usage
-----
    python3 xval_booksim_8x6.py --gen        # write topology + config files
    python3 xval_booksim_8x6.py --run        # needs src/booksim built
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RUNDIR = ROOT / "runfiles"
TOPO = RUNDIR / "mesh_8x6.anynet"
OUT = ROOT / "results" / "xval_booksim_8x6.json"
BOOKSIM = ROOT / "src" / "booksim"

MX, MY = 8, 6
H_LAT, V_LAT = 7, 9
RAMP_LAT = 2
LAMS = (0.01, 0.05, 0.1, 0.2, 0.3, 0.35, 0.4, 0.45, 0.5, 0.6)


def gen_topology(path: Path = TOPO) -> str:
    """anynet adjacency: one line per router, with per-link latency in cycles."""
    lines = []
    for y in range(MY):
        for x in range(MX):
            n = x + MX * y
            parts = [f"router {n}", f"node {n} {RAMP_LAT}"]
            for dx, dy, lat in ((1, 0, H_LAT), (-1, 0, H_LAT),
                                (0, 1, V_LAT), (0, -1, V_LAT)):
                nx, ny = x + dx, y + dy
                if 0 <= nx < MX and 0 <= ny < MY:
                    parts.append(f"router {nx + MX * ny} {lat}")
            lines.append(" ".join(parts))
    text = "\n".join(lines) + "\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    return text


def gen_config(lam: float, buf_depth: int, path: Path) -> str:
    """One config per load point.

    `injection_rate` in BookSim is per node per cycle in PACKETS when
    `injection_rate_uses_flits = 0`, matching `SteadyParams.lam`.
    """
    cfg = f"""// generated by utils/xval_booksim_8x6.py
topology = anynet;
network_file = {TOPO};
routing_function = min;

// credit-based flow control with one VC, buffers sized in flits
num_vcs = 1;
vc_buf_size = {buf_depth};
wait_for_tail_credit = 0;

// input-queued router with iSLIP switch allocation, matching MeshBaseSim
router = iq;
vc_allocator = islip;
sw_allocator = islip;
alloc_iters = 1;
credit_delay = 0;
routing_delay = 0;
vc_alloc_delay = 1;
sw_alloc_delay = 1;
st_final_delay = 0;
input_speedup = 1;
output_speedup = 1;
internal_speedup = 1.0;

traffic = uniform;
packet_size = 1;
injection_rate_uses_flits = 0;
injection_rate = {lam};

sim_type = latency;
warmup_periods = 3;
sample_period = 2000;
max_samples = 8;
sim_count = 1;
"""
    path.write_text(cfg)
    return cfg


_PAT = {
    "packet_latency": re.compile(r"Packet latency average = ([\d.]+)"),
    "network_latency": re.compile(r"Network latency average = ([\d.]+)"),
    "accepted": re.compile(r"Accepted packet rate average = ([\d.]+)"),
    "accepted_flit": re.compile(r"Accepted flit rate average = ([\d.]+)"),
    "injected": re.compile(r"Injected packet rate average = ([\d.]+)"),
}


def parse(txt: str) -> dict[str, float | bool]:
    out: dict[str, float | bool] = {}
    for k, pat in _PAT.items():
        hits = pat.findall(txt)
        if hits:
            out[k] = float(hits[-1])
    out["unstable"] = ("Simulation unstable" in txt
                       or "did not converge" in txt)
    return out


def run() -> dict:
    if not BOOKSIM.exists():
        raise SystemExit(
            f"{BOOKSIM} not built. BookSim's config parser is generated with "
            "flex and bison; install both, then run `make -C src`.")
    gen_topology()
    rows = []
    for buf_depth in (4, 8, 20):
        for lam in LAMS:
            cfg = RUNDIR / f"xval_8x6_b{buf_depth}_l{lam}.cfg"
            gen_config(lam, buf_depth, cfg)
            p = subprocess.run([str(BOOKSIM), str(cfg)], capture_output=True,
                               text=True, timeout=1800)
            row = {"lam": lam, "buf_depth": buf_depth,
                   "rc": p.returncode} | parse(p.stdout)
            rows.append(row)
            print(f"  buf={buf_depth:>2} lam={lam:<5} "
                  f"lat={row.get('packet_latency')} "
                  f"acc={row.get('accepted')} unstable={row.get('unstable')}")

    from rg_steady_des import SteadyParams, run_steady
    ours = []
    for buf_depth in (4, 8, 20):
        for lam in LAMS:
            r = run_steady("mesh_base", SteadyParams(
                lam=lam, buf_depth=buf_depth, warmup=1500, measure=6000))
            ours.append({"lam": lam, "buf_depth": buf_depth,
                         "packet_latency": r["mean_lat"],
                         "accepted": r["accepted"], "stable": r["stable"]})

    def sat(rows_, acc_key, stable_pred):
        best = 0.0
        for r in rows_:
            if stable_pred(r):
                best = max(best, r.get(acc_key) or 0.0)
        return round(best, 4)

    cmp_rows = []
    for buf_depth in (4, 8, 20):
        bs = [r for r in rows if r["buf_depth"] == buf_depth]
        us = [r for r in ours if r["buf_depth"] == buf_depth]
        zl_b = next((r.get("packet_latency") for r in sorted(
            bs, key=lambda r: r["lam"])), None)
        zl_u = next((r.get("packet_latency") for r in sorted(
            us, key=lambda r: r["lam"])), None)
        s_b = sat(bs, "accepted", lambda r: not r["unstable"])
        s_u = sat(us, "accepted", lambda r: r["stable"])
        cmp_rows.append({
            "buf_depth": buf_depth,
            "zero_load_booksim": zl_b, "zero_load_ours": zl_u,
            "zero_load_delta": (round(abs((zl_b or 0) - (zl_u or 0)), 2)
                                if zl_b and zl_u else None),
            "sat_booksim": s_b, "sat_ours": s_u,
            "sat_rel_err": (round(abs(s_b - s_u) / s_b, 3) if s_b else None),
        })
    res = {"booksim": rows, "ours": ours, "compare": cmp_rows}
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(res, indent=1))
    print(f"\nwrote {OUT}")
    for c in cmp_rows:
        print(f"  buf={c['buf_depth']:>2} zero-load {c['zero_load_booksim']} "
              f"vs {c['zero_load_ours']} (d={c['zero_load_delta']})  "
              f"sat {c['sat_booksim']} vs {c['sat_ours']} "
              f"(rel {c['sat_rel_err']})")
    return res


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--gen", action="store_true",
                    help="write topology and config files only")
    ap.add_argument("--run", action="store_true",
                    help="run BookSim and compare")
    a = ap.parse_args()
    if a.gen or not a.run:
        gen_topology()
        gen_config(0.1, 20, RUNDIR / "xval_8x6_example.cfg")
        print(f"wrote {TOPO} ({MX}x{MY}, H={H_LAT} V={V_LAT}) and "
              f"{RUNDIR / 'xval_8x6_example.cfg'}")
        if not a.run:
            sys.exit(0)
    run()
